### ISSUE TITLE
Display and switch pin layout? 

### ISSUE THREAD

**Issue by Pokemonarmy360** [Cancro29/NETHERCAP#11]
Hi this is me again I am actually working on the HTML and this time I actually want to know the pin layout for display and switches are same with the spacehuhn deauther? Or it has other pin layout? I am making a pocket version of it that's why I am asking....... 
![17116431405426023648776692507773](https://github.com/Cancro29/NETHERCAP/assets/164488537/fea1db95-3318-47c5-a4bf-a3b87d55f700)

**Comment by Pokemonarmy360** [comment]
![17116434112691405063111445055077](https://github.com/Cancro29/NETHERCAP/assets/164488537/1c7f7b65-59f9-4d4c-9e6e-7b5ff8204a6c)
Also making a big one for the ESP 32 [your version] and spacehuhn deauthor

**Comment by Cancro29** [comment]
Hello, the wiring of ESP8266 OLED looked like this :
VCC  -> 5V
GND -> G
SCL  ->  D1
SDA  -> D2

And for ESP32:
VDD  -> 3V3
GND -> GND
SCK  -> D22 
SDA  -> D21

**Comment by Pokemonarmy360** [comment]
Is there any press switch pinout for going through UI in the display?

**Comment by Cancro29** [comment]
On ESP8266, you can attach a button on pin D7.

**Comment by Pokemonarmy360** [comment]
Is there only one button in ESP 8266? Or there is other two buttons?

**Comment by Cancro29** [comment]
Only one button is supported, and the operation involves pressing and press&hold

**Comment by Pokemonarmy360** [comment]
Oh ok thx
