### ISSUE TITLE
Custom pages for Connecting/Retrying/Password Failed 

### ISSUE THREAD

**Issue by krisss117** [Cancro29/NETHERCAP#12]
Hi, it is amazing project. 

If it is possible it will be amazing to set pages for: Connecting/Retrying/Password Failed pages. 

I think You can use File Manager and set uploaded page as Connecting/Retrying/Password Failed :)

**Comment by krisss117** [comment]
I think it will be ok. Information in local language are more trusted.

**Comment by Cancro29** [comment]
Hello, I have released version 2.5 which support custom language on default captive portal and reconnecting page.

**Comment by krisss117** [comment]
Amazing! Work perfect :) 

Please add one more variable to change "Password" :) 

PS. Thanks for fast implement changes

**Comment by Cancro29** [comment]
I'm sorry, I don't understand that. Can you give me further explanation?

**Comment by krisss117** [comment]
![image](https://github.com/Cancro29/NETHERCAP/assets/66109831/854f51b1-ea93-4321-9b80-0069f6560658)

**Comment by Cancro29** [comment]
Ah yes, i forgot to add that. Thanks for reminding me

**Comment by krisss117** [comment]
Hi, text box cut words - show only first words...
![image](https://github.com/Cancro29/NETHERCAP/assets/66109831/0104c90e-599f-404c-aae0-e7fbf1ccda45)
![image](https://github.com/Cancro29/NETHERCAP/assets/66109831/4e2b91af-58d4-46a1-9fa4-baf74387919d)

**Comment by Cancro29** [comment]
Thanks for pointing it out. It will be fixed in later release
