### ISSUE TITLE
Custom Evil Twin ap name

### ISSUE THREAD

**Issue by krisss117** [Cancro29/NETHERCAP#19]
Please add feature to set custom Evil Twin AP name - like Rouge AP in settings

![image](https://github.com/Cancro29/NETHERCAP/assets/66109831/a33829cc-7210-46c4-9d85-95668a952b13)

**Comment by Cancro29** [comment]
Evil-Twin Access Point are supposed to mimic the target Access Point's name. I don't see why it should have different name

**Comment by krisss117** [comment]
To prepare AP in different location. Now i must set AP name on another device, then select it. It will be greate to prepare it on another location.
