### ISSUE TITLE
Buttons And Display Solder Management Needed

### ISSUE THREAD

**Issue by ridwan4200** [Cancro29/NETHERCAP#20]
I Flashed This Programe To Nodemcu But I Dont Know Which Gpio or D Pin Should I Solder For Display To Be Work And Also Buttons. Pls Shere The Display And button Management For Nodemcu Of This Programe

**Comment by Cancro29** [comment]
I will release a new version with display and button pin documentation

**Comment by ridwan4200** [comment]
> I will release a new version with display and button pin documentation

how much time will it take?
and where will you release it?

**Comment by Cancro29** [comment]
I have released it. Check the main page. The new firmware is currently in testing and will be released tomorrow.
