### ISSUE TITLE
Rogue AP for esp32 ,  readme and multi ap cloning 

### ISSUE THREAD

**Issue by j-e-e-v-a-n** [Cancro29/NETHERCAP#22]
Please fix Rogue AP for esp32 can you add a readme on how to use every feature and include a feature to show login credentials that has entered by the users in fake html page when connected by admin  like giving PCAP file after doing WPA/WPA2 handshake capture in https://github.com/risinek/esp32-wifi-penetration-tool  also include multiple ap cloning to confuse the wifi users if possible also add a WPA/WPA2 handshake capture

Note: Just started using this don't know what some of these do

**Comment by Cancro29** [comment]
Rogue AP will be coming soon, but PCAP capture won't come anytime soon

**Comment by j-e-e-v-a-n** [comment]
what about the beacon spammer

**Comment by Cancro29** [comment]
Beacon spammer is in lower priority list as i want to implement it first in ESP8266. CLI version? Maybe. BLE spoofer, not interested. Touch + buttons, why? Just use your smartphone.

In other words,I have limited time, limited coding skill, and there are too many variants of esp32 boards and its modules. Beside that, the SDK has a flaw that deter me from developing it. I'd rather develop the firmware for bare boards and control it with web server, as it is easier and cheaper for me and people.

**Comment by Cancro29** [comment]
I want to implement those features too, but it will take a very long time to code and test for each board version, which I couldn't. My current aim is to make esp32 version controllable through esp8266, so there is possibility to capture handshake using esp8266 with help from esp32, and possibly deauth 5 GHz wifi after esp32c5 gets released

**Comment by j-e-e-v-a-n** [comment]
Or you can make a team of devops who has the same aim as you

You can find a lot who have skill,time and  can contribute in some tg groups

**Comment by Cancro29** [comment]
RogueAP is just a fake captive portal that asks for username and password, mostly mimic social media login page. It is still being worked for ESP32, but it already works on ESP8266

**Comment by j-e-e-v-a-n** [comment]
@Cancro29 ok thanks

**Comment by BgLuc88** [comment]
Tôi thực sự mong chờ tính năng tấn công bluetooth ❤️
