### ISSUE TITLE
Nodemcu Version In oled The Language Is Indonathioan

### ISSUE THREAD

**Issue by ridwan4200** [Cancro29/NETHERCAP#23]
How To Set The Language To English In evil Twin on oled version? 
![Screenshot_2024-06-12-16-50-28-78](https://github.com/Cancro29/NETHERCAP/assets/163563664/d3d3ed25-6177-4e7f-ab8b-e54a3f22e213)

**Comment by Cancro29** [comment]
There are language option in settings

**Comment by ridwan4200** [comment]
but how i can get in setting cause im using oled display and button

**Comment by Cancro29** [comment]
Use wifi to connect to SoftAP and access 192.168.4.1 using browser

**Comment by ridwan4200** [comment]
if i change the language with browser after that if i do the evil twin in oled display without browser will it solve ?

**Comment by Cancro29** [comment]
Why don't you just try it? You can find the answer faster than waiting for my answer

**Comment by ridwan4200** [comment]
> Why don't you just try it? You can find the answer faster than waiting for my answer

did you have any other social media of your where i can ask you and you can answer faster?

**Comment by Cancro29** [comment]
You can contact me via email at nethercap.dev@gmail.com

**Comment by ridwan4200** [comment]
It worked. Thanks For You Replies And I Really Love This Project. You Can Remove This Issue Now
