### ISSUE TITLE
Dsike deauther watch

### ISSUE THREAD

**Issue by ridwan4200** [Cancro29/NETHERCAP#25]
Can I Use This Programe In Desike deauther Watch?

**Comment by Cancro29** [comment]
I think it will work properly if the display driver and button pins are the same. Otherwise, I need to assign the pin/driver manually.

**Comment by ridwan4200** [comment]
i saw the dsike deauther watch has SDA on (Gpio-4) and SCL on (Gpio-5). Will It work?

**Comment by Cancro29** [comment]
Yes

**Comment by ridwan4200** [comment]
can you give us the .ino file of this project?

**Comment by Cancro29** [comment]
No, this project is closed source
