### ISSUE TITLE
NodemCU v3  bug

### ISSUE THREAD

**Issue by Michik234** [Cancro29/NETHERCAP#28]
Please fix the bug when pressing the RST (reset) button when failing the "evil twin". AP_SSID: NETHERCAP changes to the target SSID.
 
Sometimes a bug occurs when we force restart nethercap while doing an "evil twin" the system reads AP_SSID: "," (empty) which causes AP_SSID to automatically become the previous target SSID.

 The bug occurs when we do a forced reset when the device is doing an "evil twin" but the target does not enter the passwd correctly, there is no other choice but to reset it. 

 The bug does not occur when the "Evil Twin" is successfully performed, the AP_SSID will return to NETHERCAP without bugs.

**Comment by Cancro29** [comment]
Hello, thank you for pointing out the bug. It will be fixed on later release.
