### ISSUE TITLE
This code is great but...

### ISSUE THREAD

**Issue by JackJones58** [Cancro29/NETHERCAP#3]
Please add an english version other than it, it is amazing. Thank you! ( For esp32)

**Comment by Cancro29** [comment]
English version coming soon!

**Comment by Cancro29** [comment]
Hello, English version for ESP-32 have been released. You can download it in Releases or builds directory

**Comment by JackJones58** [comment]
Thank you! Do i update using the file manager or should I just reflash it, Thanks!

**Comment by Cancro29** [comment]
You have to update it using file manager. The instruction is included on Releases page

**Comment by JackJones58** [comment]
Works like a charm but there is a very minor bug here. 
<img width="948" alt="image" src="https://github.com/Cancro29/NETHERCAP/assets/136602807/a7838c57-1d25-4283-ab1a-ac48a26aa3b5">

**Comment by Cancro29** [comment]
I have updated the file

**Comment by JackJones58** [comment]
Yes, I tried again unfortunately the problem is still there, But everything else is perfectly fine in english.

**Comment by Cancro29** [comment]
Make sure you download the file from Releases, i haven't upload the fixed file in builds directory

**Comment by JackJones58** [comment]
Ohh, I wasn't downloading it from there! I wil lt now.
