### ISSUE TITLE
free to use?

### ISSUE THREAD

**Issue by smoochiee** [Cancro29/NETHERCAP#31]
its free?

**Comment by Cancro29** [comment]
Yes. It is free to use

**Comment by smoochiee** [comment]
> Yes. It is free to use

when you release 5g?

**Comment by Cancro29** [comment]
It will be released when it is ready

**Comment by smoochiee** [comment]
> It will be released when it is ready

oh ok...ive tried the original codes its working but annoying changing mac and flashing...you have discord

**Comment by Cancro29** [comment]
No, I don't have discord

**Comment by smoochiee** [comment]
> No, I don't have discord

how you convert your code to bin on bw16?

**Comment by smoochiee** [comment]
> I used Arduino IDE to compile the code

ive tried export code to bin not working ..no output

**Comment by Cancro29** [comment]
Weird. Mine works like usual. It creates a file named km0_km4_image2.bin
