### ISSUE TITLE
Is the display connection available on esp32c3?

### ISSUE THREAD

**Issue by BgLuc88** [Cancro29/NETHERCAP#32]
Hello. I'm back. I have prepared the necessary boards to use your software. I tested on wemos d1 mini pro with ssd1306 0.96 display (display quite little information) and esp32 c2. can i connect ssd1306 display to esp32c3? What do the connected pins look like? Thank you
![2024-08-06 21 22 11](https://github.com/user-attachments/assets/b4806822-63a7-43ac-b6ca-f74104ecf004)
![2024-08-07 11 02 57](https://github.com/user-attachments/assets/66e89424-4c71-46de-82bc-4bceafd1fd5a)
![2024-08-06 19 10 18](https://github.com/user-attachments/assets/4f556281-aeae-43fa-8c2f-5ad7c4097bfa)

**Comment by Cancro29** [comment]
Hello. I only tested OLED display on ESP32 Dev Kit. Theoretically It can be connected with ESP32C3, but i need to reassign display pin, as ESP32C3 does not have GPIO 21 and GPIO 22

**Comment by n0tAv1ru5** [comment]
Can you release button wiring tutorial?
