### ISSUE TITLE
ESP8266 True Deauth

### ISSUE THREAD

**Issue by KantholzKevin** [Cancro29/NETHERCAP#33]
Have the ESP8266 the True Deauth feature like the ESP32 ?

**Comment by Cancro29** [comment]
It is not possible. True deauth requires dual-core processor so each core can handle scanning and deauthing at the same time. There is another method worth trying but I haven't tested it yet

**Comment by KantholzKevin** [comment]
How about pausing the deauth every 30 seconds to rescan and then add it?

**Comment by Cancro29** [comment]
That method is similar to deauth all.

**Comment by Cancro29** [comment]
Turns out it is easier than I thought. True Deauth will available soon on ESP8266
