### ISSUE TITLE
Issue login page

### ISSUE THREAD

**Issue by Maam5** [Cancro29/NETHERCAP#34]
Hello dear,
Hope you are doing well. I am from Bangladesh. Recently i install nethercap wifi tool on nodemcu esp8266. But i found an problem. 

That is when i action deauthor and evail twin, normally ssid change and see fake login page.  But while that process i can't manage or login 192.168.4.1 ip address to operate system. It required disconnect power and re connect.

Can you Plz give an solution. To login page during action performing.

**Comment by Cancro29** [comment]
If the captive portal does no appear after activating evil-twin, try erasing your esp8266 first using Spacehuhn's reset bin file

**Comment by Maam5** [comment]
can i login as a admin panel while evil twin attak run? like other tool
have. because 192.168.4.1 i enter it redirect to captive portal. give
sollution to enter as admin user on firmware while attak running.

**Comment by Cancro29** [comment]
Once evil twin is started, admin page gets replaced with evil twin page. You can go to 192.168.4.1/monitor to monitor and control it.
