### ISSUE TITLE
Deauth all on by default when power nodemcu (Need this feature)

### ISSUE THREAD

**Issue by nazrul67** [Cancro29/NETHERCAP#39]
I hope, this feature can be a better option than true deauther.
Undoubtedly, true deauther a good feauture because it can automatically scan and jam but one disadvantage is that we lose website connection.
But if the deauth all auto on when we power our esp8266 by default, it works as psudojammer. 
Besides, the most interesting thing is that we don't need any device like mobile, computer etc to jam the routers, just power it work as a jammer and when not need, just close the power. Without any device, it can.As well as we don't lose our website connection,we can also stop it by the website.
I hope, you understand what i want to say.Try to add this feature plzz.

**Comment by Cancro29** [comment]
The point of this project is to show what ESP8266 can do in Wi-Fi penetration testing, not for jamming networks
