### ISSUE TITLE
Wps pin cracking possible???

### ISSUE THREAD

**Issue by Rahad1069** [Cancro29/NETHERCAP#41]
is it possible wps pixie dust attack by esp32/esp8266?? If anyway possible, the feature must be recommended? I am searching in google but not any Information about it. The answer of chatgpt is possible but not assit me with code.

**Comment by Cancro29** [comment]
Pixie dust attack is currently not possible in esp8266

**Comment by Rahad1069** [comment]
> Pixie dust attack is currently not possible in esp8266

By esp32 is it possible??
