### ISSUE TITLE
Display is working but unable to  use buttons

### ISSUE THREAD

**Issue by modhack2003** [Cancro29/NETHERCAP#44]
I am using ssd1306 0.96 inch display and esp8266 nodemcu 
Which file I have to flash and what are the buttons connections

**Comment by modhack2003** [comment]
Can you please help me , how can I use the buttons? I tried as you mentioned but it didn't work.

**Comment by Danzz553** [comment]
Are you using yellow and blue oled or just blue Oled?

**Comment by modhack2003** [comment]
Only blue oled
