### ISSUE TITLE
How to access dashboard after starting attack?

### ISSUE THREAD

**Issue by needs41** [Cancro29/NETHERCAP#5]
How to access dashboard after starting attack or Rogue AP started? [192.168.4.1/admin](192.168.4.1/admin) is not accessible.it start captive portal every time.

**Comment by Cancro29** [comment]
if you have started evil twin/rogue AP, the dashboard page gets replaced
with captive portal. You cannot access it unless you disable evil
twin/rogue AP.

You can open 192.168.4.1/monitor as dashboard replacement.
