### ISSUE TITLE
Can we receive attack update on Telegram?

### ISSUE THREAD

**Issue by abdul-nnd** [Cancro29/NETHERCAP#7]
There is an entry of Telegram token in config.json file. What is it? Is it working? Is it possible to receive attack update on Telegram?

**Comment by Cancro29** [comment]
Yes it is possible, even remote control through telegram works too. But i
decided to disable it because it causes performance issue.

**Comment by abdul-nnd** [comment]
It's a very good idea to remotely control our device. We request you, Please remove such performance issues and implement it. If possible use different services other than Telegram such as Firebase or any other.

**Comment by Cancro29** [comment]
It is not possible to optimize it. Either the telegram bot will respond for
a very long time(can takes minutes) OR deauth and captive portal becoming
ineffective. Besides, that feature requires another Wi-Fi hotspot for
internet connection.

**Comment by abdul-nnd** [comment]
You can use Firebase for realtime update. Another hotspot or internet connection is not a problem, we can manage it.

**Comment by Cancro29** [comment]
I don't want to add another libraries
